// Define an array to hold various meal plans.
export const mealPlans = [
  // Each object in the array represents a meal plan for a single person.
  {
    mealOption: "vegan", // The type of meal diet.
    type: "breakfast", // The type of meal.
    name: "Vegan French Toast", // The name of the meal.
    housePricePP: 5, // The price per person at a house.
    hotelPricePP: 18, // The price per person at a hotel.
    motelPricePP: 18, // The price per person at a motel.
    hostelPricePP: 18, // The price per person at a hostel.
  },
  // Additional meal plans follow, each represented by an object in the array...
  {
    mealOption: "vegan",
    type: "lunch",
    name: "Chickpea Salad",
    housePricePP: 7,
    hotelPricePP: 20,
    motelPricePP: 20,
    hostelPricePP: 20,
  },
  {
    mealOption: "vegan",
    type: "dinner",
    name: "Vegan Lasagna",
    housePricePP: 10,
    hotelPricePP: 22,
    motelPricePP: 22,
    hostelPricePP: 22,
  },
  {
    mealOption: "vegan",
    type: "snack",
    name: "Fruit Smoothie",
    housePricePP: 3,
    hotelPricePP: 10,
    motelPricePP: 10,
    hostelPricePP: 10,
  },

  // Vegetarian meals
  {
    mealOption: "vegetarian",
    type: "breakfast",
    name: "Vegetarian Omelette",
    housePricePP: 6,
    hotelPricePP: 19,
    motelPricePP: 19,
    hostelPricePP: 19,
  },
  {
    mealOption: "vegetarian",
    type: "lunch",
    name: "Vegetable Stir Fry",
    housePricePP: 8,
    hotelPricePP: 21,
    motelPricePP: 21,
    hostelPricePP: 21,
  },
  {
    mealOption: "vegetarian",
    type: "dinner",
    name: "Vegetarian Pasta",
    housePricePP: 11,
    hotelPricePP: 24,
    motelPricePP: 24,
    hostelPricePP: 24,
  },
  {
    mealOption: "vegetarian",
    type: "snack",
    name: "Greek Yogurt with Honey and Nuts",
    housePricePP: 4,
    hotelPricePP: 12,
    motelPricePP: 12,
    hostelPricePP: 12,
  },
  // Chicken meals
  {
    mealOption: "chicken",
    type: "breakfast",
    name: "Chicken and Egg Wrap",
    housePricePP: 6,
    hotelPricePP: 19,
    motelPricePP: 19,
    hostelPricePP: 19,
  },
  {
    mealOption: "chicken",
    type: "lunch",
    name: "Grilled Chicken Salad",
    housePricePP: 8,
    hotelPricePP: 22,
    motelPricePP: 22,
    hostelPricePP: 22,
  },
  {
    mealOption: "chicken",
    type: "dinner",
    name: "Chicken Stir Fry",
    housePricePP: 12,
    hotelPricePP: 26,
    motelPricePP: 26,
    hostelPricePP: 26,
  },
  {
    mealOption: "chicken",
    type: "snack",
    name: "Chicken Skewers",
    housePricePP: 5,
    hotelPricePP: 15,
    motelPricePP: 15,
    hostelPricePP: 15,
  },

  // Red meat meals
  {
    mealOption: "red meat",
    type: "breakfast",
    name: "Bacon and Eggs",
    housePricePP: 7,
    hotelPricePP: 20,
    motelPricePP: 20,
    hostelPricePP: 20,
  },
  {
    mealOption: "red meat",
    type: "lunch",
    name: "Steak Sandwich",
    housePricePP: 10,
    hotelPricePP: 24,
    motelPricePP: 24,
    hostelPricePP: 24,
  },
  {
    mealOption: "red meat",
    type: "dinner",
    name: "Roasted Lamb Chops",
    housePricePP: 14,
    hotelPricePP: 28,
    motelPricePP: 28,
    hostelPricePP: 28,
  },
  {
    mealOption: "red meat",
    type: "snack",
    name: "Beef Jerky",
    housePricePP: 4,
    hotelPricePP: 14,
    motelPricePP: 14,
    hostelPricePP: 14,
  },

  // Beef meals
  {
    mealOption: "beef",
    type: "breakfast",
    name: "Beef Sausage and Eggs",
    housePricePP: 7,
    hotelPricePP: 20,
    motelPricePP: 20,
    hostelPricePP: 20,
  },
  {
    mealOption: "beef",
    type: "lunch",
    name: "Beef Burger",
    housePricePP: 10,
    hotelPricePP: 24,
    motelPricePP: 24,
    hostelPricePP: 24,
  },
  {
    mealOption: "beef",
    type: "dinner",
    name: "Beef Stew",
    housePricePP: 14,
    hotelPricePP: 28,
    motelPricePP: 28,
    hostelPricePP: 28,
  },
  {
    mealOption: "beef",
    type: "snack",
    name: "Beef Sliders",
    housePricePP: 6,
    hotelPricePP: 16,
    motelPricePP: 16,
    hostelPricePP: 16,
  },

  // Fish meals
  {
    mealOption: "fish",
    type: "breakfast",
    name: "Smoked Salmon Bagel",
    housePricePP: 8,
    hotelPricePP: 22,
    motelPricePP: 22,
    hostelPricePP: 22,
  },
  {
    mealOption: "fish",
    type: "lunch",
    name: "Fish Tacos",
    housePricePP: 11,
    hotelPricePP: 25,
    motelPricePP: 25,
    hostelPricePP: 25,
  },
  {
    mealOption: "fish",
    type: "dinner",
    name: "Grilled Sea Bass",
    housePricePP: 15,
    hotelPricePP: 30,
    motelPricePP: 30,
    hostelPricePP: 30,
  },
  {
    mealOption: "fish",
    type: "snack",
    name: "Shrimp Cocktail",
    housePricePP: 7,
    hotelPricePP: 18,
    motelPricePP: 18,
    hostelPricePP: 18,
  },
];

// Define an array to hold various accommodation options
export const accommodationOptions = [
  // Each object in the array represents a single accommodation option
  {
    name: "House", // The type of accommodation
    listingName: "Family Home - Stylish Sanctuary", // The name or title of the listing (not present in all objects)
    location: "Auckland", // The city where the accommodation is located
    cost: 240, // The cost per night of the accommodation
    minPeople: 1, // The minimum number of people the accommodation can host
    maxPeople: 5, // The maximum number of people the accommodation can host
    minDays: 2, // The minimum number of days the accommodation can be booked for
    maxDays: 15, // The maximum number of days the accommodation can be booked for
    image: "img/auckland/auckHouse.jpeg", // The path to an image of the accommodation (not present in all objects)
    address: "45 Hanene Street, St Heliers, Auckland 1071", // The physical address of the accommodation (not present in all objects)
    latitude: "-36.851810", // The latitude coordinate of the accommodation (not present in all objects)
    longitude: "174.849200", // The longitude coordinate of the accommodation (not present in all objects)
  },
  // Additional accommodation options follow, each represented by an object in the array...
  {
    name: "Hotel",
    listingName: "Princes Wharf Boutique",
    location: "Auckland",
    cost: 157,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "img/auckland/auckHotel.webp",
    address: "4/139 Quay Street, Auckland CBD, Auckland 1010",
    latitude: "-36.840690",
    longitude: "174.765590",
  },
  {
    name: "Hostel",
    location: "Auckland",
    cost: 30,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "img/auckland/auckHostel.jpg",
    listingName: "Choice Backpackers",
    address: "10 Wellesley Street East, Auckland CBD, Auckland City 1010",
    latitude: "-36.850930",
    longitude: "174.765150",
  },
  {
    name: "Motel",
    location: "Auckland",
    cost: 90,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "img/auckland/auckMotel.jpeg",
    listingName: "Fernz Motel & Apartments Birkenhead",
    address: "23 Rawene Road, Birkenhead, Auckland 0626",
    latitude: "-36.813510",
    longitude: "174.725780",
  },
  {
    name: "House",
    location: "Wellington",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "/img/wellington/wellingtonHouse.jpeg ",
    listingName: "Stunning Panoramic views of Wellington",
    address: "15 Countess Close, Maupuia, Wellington 6022",
    latitude: "-41.299990",
    longitude: "174.819300",
  },
  {
    name: "Hotel",
    location: "Wellington",
    cost: 150,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "/img/wellington/wellingtonHotel.avif",
    address: "28 Grey Street, Lambton Quay, Wellington 6011",
    listingName: "Double Tree by Hilton",
    latitude: "-41.284510",
    longitude: "174.775840",
  },
  {
    name: "Hostel",
    location: "Wellington",
    cost: 28,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "/img/wellington/hostelWellington.jpeg",
    listingName: "YHA Hostel",
    address: "292 Wakefield Street, Te Aro, Wellington 6011",
    latitude: "-41.2931158",
    longitude: "174.7838581",
  },
  {
    name: "Motel",
    location: "Wellington",
    cost: 85,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "/img/wellington/wellingtonMotel.jpeg",
    address: "21 Kent Terrace, Mount Victoria, Wellington 6011",
    listingName: "Halswell Lodge",
    latitude: "-41.2951188",
    longitude: "174.7837393",
  },
  {
    name: "House",
    location: "Christchurch",
    cost: 230,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Christchurch",
    cost: 145,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Christchurch",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Christchurch",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Queenstown",
    cost: 250,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Queenstown",
    cost: 160,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Queenstown",
    cost: 35,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Queenstown",
    cost: 95,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Rotorua",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Rotorua",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Rotorua",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Rotorua",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Napier",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Napier",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Napier",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Napier",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Hamilton",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Hamilton",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Hamilton",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Hamilton",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Tauranga",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Tauranga",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Tauranga",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Tauranga",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Dunedin",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Dunedin",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Dunedin",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Dunedin",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Palmerston North",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Palmerston North",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Palmerston North",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Palmerston North",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Nelson",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Nelson",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Nelson",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Nelson",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "New Plymouth",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "New Plymouth",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "New Plymouth",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "New Plymouth",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Whangarei",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Whangarei",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Whangarei",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Whangarei",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Invercargill",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Invercargill",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Invercargill",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Invercargill",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Whanganui",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Whanganui",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Whanganui",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Whanganui",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Gisborne",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Gisborne",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Gisborne",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Gisborne",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Blenheim",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Blenheim",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Blenheim",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Blenheim",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Taupo",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Taupo",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Taupo",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Taupo",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Timaru",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Timaru",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Timaru",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Timaru",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Porirua",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Porirua",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Porirua",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Porirua",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Coromandel",
    cost: 210,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Coromandel",
    cost: 130,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Coromandel",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Coromandel",
    cost: 75,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "House",
    location: "Masterton",
    cost: 220,
    minPeople: 1,
    maxPeople: 5,
    minDays: 2,
    maxDays: 15,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hotel",
    location: "Masterton",
    cost: 140,
    minPeople: 1,
    maxPeople: 2,
    minDays: 1,
    maxDays: 5,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Hostel",
    location: "Masterton",
    cost: 25,
    minPeople: 1,
    maxPeople: 1,
    minDays: 1,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
  {
    name: "Motel",
    location: "Masterton",
    cost: 80,
    minPeople: 2,
    maxPeople: 4,
    minDays: 3,
    maxDays: 10,
    image: "",
    listingName: "",
    latitude: "",
    longitude: "",
  },
];
