const accomodation = [
  {
    type: `Hotel`,
    name: `Bolton Hotel`,
    location: `Wellington`,
    address: `12 Bolton Street, Wellington Central, Wellington 6011`,
    minGuest: `1`,
    maxGuest: `2`,
    cost: `157`,
    minStay: `1`,
    maxStay: `5`,
  },
  {
    type: `Hostel`,
    name: `The Marion Hostel`,
    location: `Wellington`,
    address: `13 Marion Street, Te Aro, Wellington 6011`,
    minGuest: `1`,
    maxGuest: `2`,
    cost: `30`,
    minStay: `1`,
    maxStay: `10`,
  },
  {
    type: `Motel`,
    name: `Bella Vista Motel`,
    location: `Wellington`,
    address: `302/304 Evans Bay Parade, Hataitai, Wellington 6021`,
    minGuest: `2`,
    maxGuest: `4`,
    cost: `90`,
    minStay: `3`,
    maxStay: `10`,
  },
  {
    type: `House`,
    name: `Studio Seventy Four`,
    location: `Wellington`,
    address: `74 Mills Road, Brooklyn, Wellington 6021`,
    minGuest: `1`,
    maxGuest: `4`,
    cost: `240`,
    minStay: `2`,
    maxStay: `15`,
  },

  {
    type: `Hotel`,
    name: `Hotel Fitzroy curated by Fable`,
    location: `Auckland`,
    address: `43 Richmond Road, Grey Lynn, Auckland 1021`,
    minGuest: `1`,
    maxGuest: `2`,
    cost: `157`,
    minStay: `1`,
    maxStay: `5`,
  },
  {
    type: `Hostel`,
    name: `Haka Lodge`,
    location: `Auckland`,
    address: ``,
    minGuest: `1`,
    maxGuest: `2`,
    cost: `30`,
    minStay: `1`,
    maxStay: `10`,
  },
  {
    type: `Motel`,
    name: `FRENZ Motel & Appartments Birkenhead`,
    location: `Auckland`,
    address: `23 Rawene Road, Birkenhead, Auckland 0626`,
    minGuest: `2`,
    maxGuest: `4`,
    cost: `90`,
    minStay: `3`,
    maxStay: `10`,
  },
  {
    type: `House`,
    name: `Stay Mission Bay`,
    location: `Auckland`,
    address: `9 Patteson Avenue, Mission Bay, Auckland 1071`,
    minGuest: `1`,
    maxGuest: `4`,
    cost: `240`,
    minStay: `2`,
    maxStay: `15`,
  },
];

const meals = [
  {
    type: `Vegan`,
    food: ``,
  },
];
